# Generated by Django 3.1.7 on 2021-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0002_auto_20210408_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchart',
            name='section',
            field=models.CharField(default=2, max_length=120, verbose_name='datesection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workchart',
            name='metin',
            field=models.CharField(max_length=120, verbose_name='projeler'),
        ),
    ]
