# Generated by Django 3.1.7 on 2021-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0003_auto_20210408_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchart',
            name='project',
            field=models.TextField(default=2, max_length=120, verbose_name='Proje'),
            preserve_default=False,
        ),
    ]
