# Generated by Django 3.1.7 on 2021-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0005_workchart_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchart',
            name='content',
            field=models.CharField(default=2, max_length=120, verbose_name='datesection'),
            preserve_default=False,
        ),
    ]
