# Generated by Django 3.1.7 on 2021-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0006_workchart_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchart',
            name='projectpart',
            field=models.CharField(default=2, max_length=120, verbose_name='datesection'),
            preserve_default=False,
        ),
    ]
