# Generated by Django 3.1.7 on 2021-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0007_workchart_projectpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workchart',
            name='metin',
        ),
    ]
