# Generated by Django 3.1.7 on 2021-04-09 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0011_auto_20210409_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='datetime1',
            field=models.DateField(default=datetime.date.today, verbose_name='datetime'),
        ),
    ]
