# Generated by Django 3.1.7 on 2021-04-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0012_auto_20210409_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='datetime1',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='datetime'),
        ),
    ]
