# Generated by Django 3.1.7 on 2021-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0014_auto_20210409_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='datetime1',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime1'),
        ),
    ]
