# Generated by Django 3.1.7 on 2021-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0017_auto_20210409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='datetime1',
            field=models.DateField(null='True', verbose_name='datetime1'),
        ),
    ]
