# Generated by Django 3.1.7 on 2021-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0018_auto_20210409_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='datetime1',
            field=models.CharField(default=2, max_length=120, verbose_name='datetime1'),
            preserve_default=False,
        ),
    ]
