# Generated by Django 3.1.7 on 2021-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0021_auto_20210409_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workchart',
            name='datetime1',
        ),
        migrations.AddField(
            model_name='workchart',
            name='datetime',
            field=models.DateField(null='True', verbose_name='datetime'),
            preserve_default='True',
        ),
    ]
