# Generated by Django 3.1.7 on 2021-04-09 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workblog', '0022_auto_20210409_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
