# Generated by Django 3.1.7 on 2021-04-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0023_workchart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchart',
            name='content',
            field=models.CharField(max_length=120, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='workchart',
            name='project',
            field=models.TextField(max_length=120, null='True', verbose_name='Proje'),
        ),
    ]
