# Generated by Django 3.1.7 on 2021-04-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0024_auto_20210410_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workchart',
            options={'ordering': ['datetime']},
        ),
    ]
